const data = [
  {
    "Type": "Closed IDE",
    "Name": "Cursor",
    "Category": "IDE fork with AI features",
    "Brief Purpose/Description": "VSCode fork with built-in AI chat, codegen, and Q&A on local codebases. Designed for seamless dev workflows.",
    "Architecture": "Electron/JS",
    "Purpose": "AI coding/gen chat",
    "Price": "Free / Paid",
    "Local Use": "Yes*",
    "Open Source": "No",
    "IDE Integration": "N/A (own IDE)",
    "Standalone/Install": "Yes (native app)",
    "Edu Discount": "Yes (students)",
    "Multi-user": "Yes (students)",
    "Codebase Exploration": "Yes (chat, search, AI, Q&A)",
    "Code Assist": "Yes (AI)",
    "APIs": "No",
    "Integration Points": "N/A (own IDE)",
    "Educational Suitability": "Excellent (students, teams)",
    "correction": "(Local Use Yes) Partially true — Cursor itself requires VSCode, some features are online-only."
  },
  {
    "Type": "Closed IDE",
    "Name": "Replit",
    "Category": "Online IDE with AI agents",
    "Brief Purpose/Description": "Cloud IDE with ghostwriter AI, collaborative coding, and instant project deployment.",
    "Architecture": "Web SaaS",
    "Purpose": "AI-assisted online IDE",
    "Price": "Free / Paid",
    "Local Use": "No",
    "Open Source": "No",
    "IDE Integration": "Yes (inbuilt IDE)",
    "Standalone/Install": "Web only",
    "Edu Discount": "Yes",
    "Multi-user": "Yes",
    "Codebase Exploration": "Yes (AI autocomplete/Q&A)",
    "Code Assist": "Yes (AI)",
    "APIs": "Yes",
    "Integration Points": "Native + API",
    "Educational Suitability": "Excellent for learning & collaboration",
    "correction": "(Multi-User:Yes) This is true for collaborative projects and teams."
  },
  {
    "Type": "Closed IDE",
    "Name": "Windsurf",
    "Category": "Web/Hybrid IDE + Code Search",
    "Brief Purpose/Description": "Intelligent codebase interpreter with support for local/dev use.",
    "Architecture": "Docker/Node",
    "Purpose": "AI codebase intelligence",
    "Price": "Free / Paid",
    "Local Use": "Yes",
    "Open Source": "No",
    "IDE Integration": "Plugin",
    "Standalone/Install": "Web/hybrid",
    "Edu Discount": "-",
    "Multi-user": "-",
    "Codebase Exploration": "Yes",
    "Code Assist": "Yes",
    "APIs": "API Keys",
    "Integration Points": "Plugin",
    "Educational Suitability": "Good for hybrid or local use",
    "correction": "(Local Use Yes) Requires setup for local use — Docker support is required."
  },
  {
    "Type": "Code Assist",
    "Name": "OpenAI ChatGPT",
    "Category": "Web Chat + Code Assistant",
    "Brief Purpose/Description": "Versatile chat interface for code, learning, and Q&A",
    "Architecture": "Cloud",
    "Purpose": "Code assistance, Q&A",
    "Price": "Free / Paid",
    "Local Use": "No",
    "Open Source": "No",
    "IDE Integration": "No",
    "Standalone/Install": "Web only",
    "Edu Discount": "-",
    "Multi-user": "Yes",
    "Codebase Exploration": "Yes",
    "Code Assist": "Yes (AI)",
    "APIs": "Yes",
    "Integration Points": "Web",
    "Educational Suitability": "Good general-purpose option",
    "correction": "(Code Assist: Yes) This is true for ChatGPT Pro and API."
  },
  {
    "Type": "Code Assist",
    "Name": "GitHub Copilot",
    "Category": "IDE plugin/assistant",
    "Brief Purpose/Description": "Cloud-hosted AI autocomplete and inline suggestions",
    "Architecture": "Cloud, Plugins",
    "Purpose": "IDE-based code assist",
    "Price": "Paid (Free for students)",
    "Local Use": "No",
    "Open Source": "No",
    "IDE Integration": "Yes (VSCode, JetBrains)",
    "Standalone/Install": "Plugin only",
    "Edu Discount": "Yes",
    "Multi-user": "Yes",
    "Codebase Exploration": "Yes (AI Q&A)",
    "Code Assist": "Yes (AI)",
    "APIs": "Yes",
    "Integration Points": "IDE plugins",
    "Educational Suitability": "Excellent (if policy allows cloud)",
    "correction": "(Edu Discount Yes) Free only for verified students/teachers."
  },
  {
    "Type": "Code Assist",
    "Name": "Cline",
    "Category": "Open-source AI CLI",
    "Brief Purpose/Description": "Fast local command-line chat with code interpreter and file support.",
    "Architecture": "Rust, Python",
    "Purpose": "Local AI chat & code",
    "Price": "Free",
    "Local Use": "Yes",
    "Open Source": "Yes",
    "IDE Integration": "-",
    "Standalone/Install": "Yes (native, pip)",
    "Edu Discount": "-",
    "Multi-user": "-",
    "Codebase Exploration": "Partial (file chat)",
    "Code Assist": "Yes",
    "APIs": "Yes (local)",
    "Integration Points": "CLI",
    "Educational Suitability": "Good for scripting, CLI learners",
    "correction": ""
  },
  {
    "Type": "Code Assist",
    "Name": "Blackbox.ai",
    "Category": "IDE plugin/AI tool",
    "Brief Purpose/Description": "AI code search, code generation, and code explanation.",
    "Architecture": "Cloud, Plugin",
    "Purpose": "Code search/gen/explain",
    "Price": "Free / Paid",
    "Local Use": "No",
    "Open Source": "No",
    "IDE Integration": "Yes (many IDEs)",
    "Standalone/Install": "Plugin",
    "Edu Discount": "Yes",
    "Multi-user": "-",
    "Codebase Exploration": "Yes",
    "Code Assist": "Yes (AI)",
    "APIs": "Yes",
    "Integration Points": "IDE plugins",
    "Educational Suitability": "Good for code learning, plugin",
    "correction": ""
  },
  {
    "Type": "Code Assist",
    "Name": "GenieGPT",
    "Category": "Multi-modal AI",
    "Brief Purpose/Description": "Chatbot supporting code, text, image, web browsing, PDF & audio transcription.",
    "Architecture": "Cloud, Plugins",
    "Purpose": "Multi-modal chat/assist",
    "Price": "Free / Paid",
    "Local Use": "No",
    "Open Source": "No",
    "IDE Integration": "-",
    "Standalone/Install": "Web, API",
    "Edu Discount": "-",
    "Multi-user": "Yes",
    "Codebase Exploration": "Yes (upload)",
    "Code Assist": "Yes (AI)",
    "APIs": "Yes",
    "Integration Points": "Web, API",
    "Educational Suitability": "Good for accessibility, file upload",
    "correction": ""
  },
  {
    "Type": "Code Assist",
    "Name": "Amazon Q Developer",
    "Category": "IDE plugin/assistant",
    "Brief Purpose/Description": "Code suggestions, codebase Q&A, code transformation and cloud ops.",
    "Architecture": "Cloud, Plugin",
    "Purpose": "IDE code assist/ops",
    "Price": "Paid",
    "Local Use": "No",
    "Open Source": "No",
    "IDE Integration": "Yes (JetBrains, VSCode, CLI)",
    "Standalone/Install": "Plugin/CLI",
    "Edu Discount": "-",
    "Multi-user": "-",
    "Codebase Exploration": "Yes (Q&A)",
    "Code Assist": "Yes (AI)",
    "APIs": "Yes",
    "Integration Points": "IDE plugins, CLI",
    "Educational Suitability": "Good for enterprise/large teams",
    "correction": ""
  },
  {
    "Type": "Code Assist",
    "Name": "Claude (Anthropic)",
    "Category": "Web Chat + API",
    "Brief Purpose/Description": "Large context, safe AI chatbot with strong code/logic capability.",
    "Architecture": "Cloud",
    "Purpose": "Chat, code, logic",
    "Price": "Free / Paid",
    "Local Use": "No",
    "Open Source": "No",
    "IDE Integration": "-",
    "Standalone/Install": "Web only",
    "Edu Discount": "-",
    "Multi-user": "Yes",
    "Codebase Exploration": "Yes (upload)",
    "Code Assist": "Yes (AI)",
    "APIs": "Yes",
    "Integration Points": "Web, API",
    "Educational Suitability": "Good for large docs, multi-file",
    "correction": ""
  },
  {
    "Type": "Code Assist",
    "Name": "Sourcegraph Cody",
    "Category": "IDE plugin/assistant",
    "Brief Purpose/Description": "AI code search, autocomplete and Q&A for codebases.",
    "Architecture": "Cloud, Plugin",
    "Purpose": "Code search/assist",
    "Price": "Free / Paid",
    "Local Use": "No",
    "Open Source": "No",
    "IDE Integration": "Yes (many IDEs)",
    "Standalone/Install": "Plugin, Web",
    "Edu Discount": "-",
    "Multi-user": "-",
    "Codebase Exploration": "Yes",
    "Code Assist": "Yes (AI)",
    "APIs": "Yes",
    "Integration Points": "IDE plugins, Web",
    "Educational Suitability": "Great for large codebases",
    "correction": ""
  },
  {
    "Type": "Code Assist",
    "Name": "Tabnine",
    "Category": "IDE plugin",
    "Brief Purpose/Description": "AI-based code completion, private model option, and IDE plugin.",
    "Architecture": "Cloud, Local",
    "Purpose": "Code assist, completions",
    "Price": "Free / Paid",
    "Local Use": "Yes",
    "Open Source": "No",
    "IDE Integration": "Yes (many IDEs)",
    "Standalone/Install": "Plugin",
    "Edu Discount": "Yes",
    "Multi-user": "Yes",
    "Codebase Exploration": "-",
    "Code Assist": "Yes (AI)",
    "APIs": "-",
    "Integration Points": "IDE plugins",
    "Educational Suitability": "Good (can be self-hosted)",
    "correction": "(Local Use: Yes) Enterprise version allows self-hosted models."
  },
  {
    "Type": "Platform",
    "Name": "Pinokio.co",
    "Category": "Local App Launcher",
    "Brief Purpose/Description": "One-click installer and manager for open-source AI/LLM apps.",
    "Architecture": "Electron/Node",
    "Purpose": "Launch/host local AI apps",
    "Price": "Free",
    "Local Use": "Yes",
    "Open Source": "Partial",
    "IDE Integration": "-",
    "Standalone/Install": "Yes (native app)",
    "Edu Discount": "-",
    "Multi-user": "-",
    "Codebase Exploration": "-",
    "Code Assist": "-",
    "APIs": "No",
    "Integration Points": "Launcher",
    "Educational Suitability": "Best for workshops, hackathons",
    "correction": ""
  },
  {
    "Type": "Platform",
    "Name": "LocalAI",
    "Category": "Local LLM Backend (API/CLI)",
    "Brief Purpose/Description": "Self-hosted API server for running local LLMs with OpenAI-compatible endpoints.",
    "Architecture": "Go, Docker",
    "Purpose": "Self-host LLM API",
    "Price": "Free",
    "Local Use": "Yes",
    "Open Source": "Yes",
    "IDE Integration": "-",
    "Standalone/Install": "Yes (Docker, Binary)",
    "Edu Discount": "-",
    "Multi-user": "Yes",
    "Codebase Exploration": "-",
    "Code Assist": "Yes",
    "APIs": "Yes (OpenAI compatible)",
    "Integration Points": "API",
    "Educational Suitability": "Great for school/private LLMs",
    "correction": ""
  },
  {
    "Type": "Platform",
    "Name": "Ollama",
    "Category": "Local LLM Manager (API)",
    "Brief Purpose/Description": "Easy-to-use CLI and server for running local LLMs (Mac, Win, Linux).",
    "Architecture": "Go",
    "Purpose": "Run local LLMs",
    "Price": "Free",
    "Local Use": "Yes",
    "Open Source": "Partial",
    "IDE Integration": "-",
    "Standalone/Install": "Yes (native app)",
    "Edu Discount": "-",
    "Multi-user": "-",
    "Codebase Exploration": "-",
    "Code Assist": "Yes",
    "APIs": "Yes (local)",
    "Integration Points": "CLI, API",
    "Educational Suitability": "Good for teaching, personal LLMs",
    "correction": ""
  },
  {
    "Type": "Platform",
    "Name": "OpenWebUI",
    "Category": "Local Web UI for LLMs",
    "Brief Purpose/Description": "Web user interface for Ollama, LM Studio, and OpenAI-compatible LLMs.",
    "Architecture": "Node, Docker",
    "Purpose": "Web UI for LLMs",
    "Price": "Free",
    "Local Use": "Yes",
    "Open Source": "Yes",
    "IDE Integration": "-",
    "Standalone/Install": "Yes (Docker, Node)",
    "Edu Discount": "-",
    "Multi-user": "Yes",
    "Codebase Exploration": "-",
    "Code Assist": "Yes",
    "APIs": "Yes (local)",
    "Integration Points": "API",
    "Educational Suitability": "Great for student labs, workshops",
    "correction": ""
  },
  {
    "Type": "Platform",
    "Name": "app.big_agi.com",
    "Category": "Web-hosted Agent IDE",
    "Brief Purpose/Description": "Full-featured open-source web UI for OpenAI-compatible LLMs and agents.",
    "Architecture": "Node, Docker",
    "Purpose": "Web UI for LLMs/agents",
    "Price": "Free",
    "Local Use": "Yes",
    "Open Source": "Yes",
    "IDE Integration": "-",
    "Standalone/Install": "Yes (Docker, Node)",
    "Edu Discount": "-",
    "Multi-user": "Yes",
    "Codebase Exploration": "-",
    "Code Assist": "Yes",
    "APIs": "Yes (local)",
    "Integration Points": "API",
    "Educational Suitability": "Excellent for advanced labs",
    "correction": ""
  }
];
